/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package iuGrafica;

import dominio.UsuarioAdministrador;

/**
 *
 * @author gonzalobazzi
 */
public class UIMenuAdministrador extends javax.swing.JDialog {
    
    private UsuarioAdministrador usuarioAdministrador;

    /**
     * Creates new form UIMenuAdministrador
     */
    public UIMenuAdministrador(java.awt.Frame parent, boolean modal, UsuarioAdministrador usuarioAdministrador) {
        super(parent, modal);
        this.usuarioAdministrador = usuarioAdministrador;
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAdministrador = new javax.swing.JMenu();
        jEmularTransito = new javax.swing.JMenuItem();
        jEmularAprobacionRecargas = new javax.swing.JMenuItem();
        jAsignarBonificaciones = new javax.swing.JMenuItem();
        jSalirAplicacion = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jMenuAdministrador.setText("Menu Administrador");

        jEmularTransito.setText("Emular Tránsito");
        jEmularTransito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmularTransitoActionPerformed(evt);
            }
        });
        jMenuAdministrador.add(jEmularTransito);

        jEmularAprobacionRecargas.setText("Emular aprobación de recargas");
        jEmularAprobacionRecargas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmularAprobacionRecargasActionPerformed(evt);
            }
        });
        jMenuAdministrador.add(jEmularAprobacionRecargas);

        jAsignarBonificaciones.setText("Asignar bonificaciones");
        jAsignarBonificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAsignarBonificacionesActionPerformed(evt);
            }
        });
        jMenuAdministrador.add(jAsignarBonificaciones);

        jSalirAplicacion.setText("Salir de la aplicación");
        jSalirAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirAplicacionActionPerformed(evt);
            }
        });
        jMenuAdministrador.add(jSalirAplicacion);

        jMenuBar1.add(jMenuAdministrador);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEmularAprobacionRecargasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmularAprobacionRecargasActionPerformed
        new UIEmularAprobacionRecarga(null,false, usuarioAdministrador).setVisible(true);
    }//GEN-LAST:event_jEmularAprobacionRecargasActionPerformed

    private void jAsignarBonificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAsignarBonificacionesActionPerformed
        new UIAsignarBonificaciones(null,false).setVisible(true);
    }//GEN-LAST:event_jAsignarBonificacionesActionPerformed

    private void jSalirAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirAplicacionActionPerformed
        //CLOSE APLICATION
    }//GEN-LAST:event_jSalirAplicacionActionPerformed

    private void jEmularTransitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmularTransitoActionPerformed
        new UIEmularTransito(null,false).setVisible(true);
    }//GEN-LAST:event_jEmularTransitoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAsignarBonificaciones;
    private javax.swing.JMenuItem jEmularAprobacionRecargas;
    private javax.swing.JMenuItem jEmularTransito;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenuAdministrador;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jSalirAplicacion;
    // End of variables declaration//GEN-END:variables
}
