/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuGrafica.celdas;

/**
 *
 * @author sebita
 */
public class CeldaVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form CeldaVehiculo
     */
    public CeldaVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMatricula = new javax.swing.JLabel();
        jModelo = new javax.swing.JLabel();
        jColor = new javax.swing.JLabel();
        jTransitos = new javax.swing.JLabel();
        jMontoTotal = new javax.swing.JLabel();

        jMatricula.setText("jLabel1");

        jModelo.setText("jLabel2");

        jColor.setText("jLabel3");

        jTransitos.setText("jLabel4");

        jMontoTotal.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jMatricula)
                .addGap(40, 40, 40)
                .addComponent(jModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jTransitos)
                .addGap(50, 50, 50)
                .addComponent(jMontoTotal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMatricula)
                    .addComponent(jModelo)
                    .addComponent(jColor)
                    .addComponent(jTransitos)
                    .addComponent(jMontoTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jColor;
    public javax.swing.JLabel jMatricula;
    public javax.swing.JLabel jModelo;
    public javax.swing.JLabel jMontoTotal;
    public javax.swing.JLabel jTransitos;
    // End of variables declaration//GEN-END:variables
}
