/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuGrafica.celdas;

/**
 *
 * @author Digital
 */
public class CeldaRecargasss extends javax.swing.JPanel {

    /**
     * Creates new form CeldaRecargasss
     */
    public CeldaRecargasss() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFechaRecarga = new javax.swing.JLabel();
        jMonto = new javax.swing.JLabel();
        jEstado = new javax.swing.JLabel();
        jAdministrador = new javax.swing.JLabel();

        jFechaRecarga.setText("jLabel1");

        jMonto.setText("jLabel1");

        jEstado.setText("jLabel1");

        jAdministrador.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jFechaRecarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jMonto)
                .addGap(113, 113, 113)
                .addComponent(jEstado)
                .addGap(120, 120, 120)
                .addComponent(jAdministrador)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAdministrador)
                    .addComponent(jEstado)
                    .addComponent(jMonto)
                    .addComponent(jFechaRecarga))
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jAdministrador;
    public javax.swing.JLabel jEstado;
    public javax.swing.JLabel jFechaRecarga;
    public javax.swing.JLabel jMonto;
    // End of variables declaration//GEN-END:variables
}
