/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuGrafica.celdas;

/**
 *
 * @author gonzalobazzi
 */
public class CeldaVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form CeldaVehiculo
     */
    public CeldaVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColor = new javax.swing.JLabel();
        jMatricula = new javax.swing.JLabel();
        jModelo = new javax.swing.JLabel();
        jMontoTotal = new javax.swing.JLabel();
        jTransitos = new javax.swing.JLabel();

        jColor.setText("jLabel1");

        jMatricula.setText("jLabel1");

        jModelo.setText("jLabel1");

        jMontoTotal.setText("jLabel1");

        jTransitos.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMatricula)
                .addGap(18, 18, 18)
                .addComponent(jModelo)
                .addGap(18, 18, 18)
                .addComponent(jColor)
                .addGap(18, 18, 18)
                .addComponent(jTransitos)
                .addGap(18, 18, 18)
                .addComponent(jMontoTotal)
                .addContainerGap(346, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jColor)
                    .addComponent(jMatricula)
                    .addComponent(jModelo)
                    .addComponent(jMontoTotal)
                    .addComponent(jTransitos))
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jColor;
    public javax.swing.JLabel jMatricula;
    public javax.swing.JLabel jModelo;
    public javax.swing.JLabel jMontoTotal;
    public javax.swing.JLabel jTransitos;
    // End of variables declaration//GEN-END:variables
}
